~ "high-scores.ua" ~ HighScores

# List of scores
⍤⤙≍ [30 50 20 70] scores [30 50 20 70]

# Latest score
⍤⤙≍ 30 latest [100 0 90 30]

# Personal best
⍤⤙≍ 100 personalBest [40 100 70]

# Personal top three from a list of scores
⍤⤙≍ [100 90 70] personalTopThree [10 30 90 30 100 20 10 0 30 40 40 70 70]

# Personal top highest to lowest
⍤⤙≍ [30 20 10] personalTopThree [20 10 30]

# Personal top when there is a tie
⍤⤙≍ [40 40 30] personalTopThree [40 20 40 30]

# Personal top when there are less than 3
⍤⤙≍ [70 30] personalTopThree [30 70]

# Personal top when there is only one
⍤⤙≍ [40] personalTopThree [40]

