~ "roman-numerals.ua" ~ RomanNumerals

# 1 is I
    roman 1 |> should equal "I"

# 2 is II
    roman 2 |> should equal "II"

# 3 is III
    roman 3 |> should equal "III"

# 4 is IV
    roman 4 |> should equal "IV"

# 5 is V
    roman 5 |> should equal "V"

# 6 is VI
    roman 6 |> should equal "VI"

# 9 is IX
    roman 9 |> should equal "IX"

# 16 is XVI
    roman 16 |> should equal "XVI"

# 27 is XXVII
    roman 27 |> should equal "XXVII"

# 48 is XLVIII
    roman 48 |> should equal "XLVIII"

# 49 is XLIX
    roman 49 |> should equal "XLIX"

# 59 is LIX
    roman 59 |> should equal "LIX"

# 66 is LXVI
    roman 66 |> should equal "LXVI"

# 93 is XCIII
    roman 93 |> should equal "XCIII"

# 141 is CXLI
    roman 141 |> should equal "CXLI"

# 163 is CLXIII
    roman 163 |> should equal "CLXIII"

# 166 is CLXVI
    roman 166 |> should equal "CLXVI"

# 402 is CDII
    roman 402 |> should equal "CDII"

# 575 is DLXXV
    roman 575 |> should equal "DLXXV"

# 666 is DCLXVI
    roman 666 |> should equal "DCLXVI"

# 911 is CMXI
    roman 911 |> should equal "CMXI"

# 1024 is MXXIV
    roman 1024 |> should equal "MXXIV"

# 1666 is MDCLXVI
    roman 1666 |> should equal "MDCLXVI"

# 3000 is MMM
    roman 3000 |> should equal "MMM"

# 3001 is MMMI
    roman 3001 |> should equal "MMMI"

# 3999 is MMMCMXCIX
    roman 3999 |> should equal "MMMCMXCIX"

