~ "roman-numerals.ua" ~ RomanNumerals

# 1 is I
⍤⤙≍ "I" roman 1

# 2 is II
⍤⤙≍ "II" roman 2

# 3 is III
⍤⤙≍ "III" roman 3

# 4 is IV
⍤⤙≍ "IV" roman 4

# 5 is V
⍤⤙≍ "V" roman 5

# 6 is VI
⍤⤙≍ "VI" roman 6

# 9 is IX
⍤⤙≍ "IX" roman 9

# 16 is XVI
⍤⤙≍ "XVI" roman 16

# 27 is XXVII
⍤⤙≍ "XXVII" roman 27

# 48 is XLVIII
⍤⤙≍ "XLVIII" roman 48

# 49 is XLIX
⍤⤙≍ "XLIX" roman 49

# 59 is LIX
⍤⤙≍ "LIX" roman 59

# 66 is LXVI
⍤⤙≍ "LXVI" roman 66

# 93 is XCIII
⍤⤙≍ "XCIII" roman 93

# 141 is CXLI
⍤⤙≍ "CXLI" roman 141

# 163 is CLXIII
⍤⤙≍ "CLXIII" roman 163

# 166 is CLXVI
⍤⤙≍ "CLXVI" roman 166

# 402 is CDII
⍤⤙≍ "CDII" roman 402

# 575 is DLXXV
⍤⤙≍ "DLXXV" roman 575

# 666 is DCLXVI
⍤⤙≍ "DCLXVI" roman 666

# 911 is CMXI
⍤⤙≍ "CMXI" roman 911

# 1024 is MXXIV
⍤⤙≍ "MXXIV" roman 1024

# 1666 is MDCLXVI
⍤⤙≍ "MDCLXVI" roman 1666

# 3000 is MMM
⍤⤙≍ "MMM" roman 3000

# 3001 is MMMI
⍤⤙≍ "MMMI" roman 3001

# 3999 is MMMCMXCIX
⍤⤙≍ "MMMCMXCIX" roman 3999

