# Cross-track labels
- name: "x:type/docs"
  description: "Work on Documentation"
  color: "604fcd"

- name: "x:type/ci"
  description: "Work on Continuous Integration (e.g. GitHub Actions workflows)"
  color: "604fcd"

- name: "x:type/docker"
  description: "Work on Dockerfiles"
  color: "604fcd"

- name: "x:type/coding"
  description: "Work on code that will run in production"
  color: "604fcd"

- name: "x:type/content"
  description: "Work on content (e.g. exercises, concepts)"
  color: "604fcd"

- name: "x:action/create"
  description: "Working on something from scratch"
  color: "6f60d2"

- name: "x:action/sync"
  description: "Syncing content with its latest version"
  color: "6f60d2"

- name: "x:action/improve"
  description: "Improve existing functionality/content"
  color: "6f60d2"

- name: "x:action/proofread"
  description: "Proofread text"
  color: "6f60d2"

- name: "x:action/fix"
  description: "Fix an issue"
  color: "6f60d2"

- name: "x:size/xs"
  description: "Smallest amount of work"
  color: "5240c9"

- name: "x:size/s"
  description: "Small amount of work"
  color: "5240c9"

- name: "x:size/m"
  description: "Average amount of work"
  color: "5240c9"

- name: "x:size/l"
  description: "Large amount of work"
  color: "5240c9"

- name: "x:size/xl"
  description: "Largest amount of work"
  color: "5240c9"

- name: "x:knowledge/newbie"
  description: "No existing Exercism knowledge required"
  color: "4836bf"

- name: "x:knowledge/beginner"
  description: "Little Exercism knowledge required"
  color: "4836bf"

- name: "x:knowledge/intermediate"
  description: "Quite a bit of Exercism knowledge required"
  color: "4836bf"

- name: "x:knowledge/advanced"
  description: "Comprehensive Exercism knowledge required"
  color: "4836bf"

- name: "x:module/generator"
  description: "Task involves working on Exercise generators"
  color: "4231af"

- name: "x:module/concept-exercise"
  description: "Task involves working on Concept Exercises"
  color: "4231af"

- name: "x:module/practice-exercise"
  description: "Task involves working on Practice Exercises"
  color: "4231af"

- name: "x:module/concept"
  description: "Task involves working on Concepts"
  color: "4231af"

- name: "x:module/test-runner"
  description: "Task involves working on Test Runners"
  color: "4231af"

- name: "x:module/representer"
  description: "Task involves working on Representers"
  color: "4231af"

- name: "x:module/analyzer"
  description: "Task involves working on Analyzers"
  color: "4231af"

- name: "x:status/claimed"
  description: "Someone is already working on this issue"
  color: "7e70d7"

# Existing labels
- name: "bug"
  description: ""
  color: "fc2929"

- name: "dependencies"
  description: "Pull requests that update a dependency file"
  color: "0025ff"

- name: "duplicate"
  description: ""
  color: "cccccc"

- name: "enhancement"
  description: ""
  color: "84b6eb"

- name: "good first issue"
  description: ""
  color: "159818"

- name: "hacktoberfest"
  description: ""
  color: "ff4500"

- name: "help wanted"
  description: ""
  color: "159818"

- name: "invalid"
  description: ""
  color: "e6e6e6"

- name: "pinned"
  description: ""
  color: "cccccc"

- name: "question"
  description: ""
  color: "cc317c"

- name: "v3-migration 🤖"
  description: "Preparing for Exercism v3"
  color: "E99695"

- name: "waiting-for-external"
  description: ""
  color: "d4c5f9"

- name: "wontfix"
  description: ""
  color: "ffffff"
