~ "scale-generator.ua" ~ ScaleGenerator

# Chromatic scale with sharps
⍤⤙≍ ["C" "C#" "D" "D#" "E" "F" "F#" "G" "G#" "A" "A#" "B"] chromatic "C"

# Chromatic scale with flats
⍤⤙≍ ["F" "Gb" "G" "Ab" "A" "Bb" "B" "C" "Db" "D" "Eb" "E"] chromatic "F"

# Simple major scale
⍤⤙≍ ["C" "D" "E" "F" "G" "A" "B" "C"] interval "MMmMMMm" "C"

# Major scale with sharps
⍤⤙≍ ["G" "A" "B" "C" "D" "E" "F#" "G"] interval "MMmMMMm" "G"

# Major scale with flats
⍤⤙≍ ["F" "G" "A" "Bb" "C" "D" "E" "F"] interval "MMmMMMm" "F"

# Minor scale with sharps
⍤⤙≍ ["F#" "G#" "A" "B" "C#" "D" "E" "F#"] interval "MmMMmMM" "f#"

# Minor scale with flats
⍤⤙≍ ["Bb" "C" "Db" "Eb" "F" "Gb" "Ab" "Bb"] interval "MmMMmMM" "bb"

# Dorian mode
⍤⤙≍ ["D" "E" "F" "G" "A" "B" "C" "D"] interval "MmMMMmM" "d"

# Mixolydian mode
⍤⤙≍ ["Eb" "F" "G" "Ab" "Bb" "C" "Db" "Eb"] interval "MMmMMmM" "Eb"

# Lydian mode
⍤⤙≍ ["A" "B" "C#" "D#" "E" "F#" "G#" "A"] interval "MMMmMMm" "a"

# Phrygian mode
⍤⤙≍ ["E" "F" "G" "A" "B" "C" "D" "E"] interval "mMMMmMM" "e"

# Locrian mode
⍤⤙≍ ["G" "Ab" "Bb" "C" "Db" "Eb" "F" "G"] interval "mMMmMMM" "g"

# Harmonic minor
⍤⤙≍ ["D" "E" "F" "G" "A" "Bb" "Db" "D"] interval "MmMMmAm" "d"

# Octatonic
⍤⤙≍ ["C" "D" "D#" "F" "F#" "G#" "A" "B" "C"] interval "MmMmMmMm" "C"

# Hexatonic
⍤⤙≍ ["Db" "Eb" "F" "G" "A" "B" "Db"] interval "MMMMMM" "Db"

# Pentatonic
⍤⤙≍ ["A" "B" "C#" "E" "F#" "A"] interval "MMAMA" "A"

# Enigmatic
⍤⤙≍ ["G" "G#" "B" "C#" "D#" "F" "F#" "G"] interval "mAMMMmm" "G"

