~ "atbash-cipher.ua" ~ AtbashCipher

# Encode yes
⍤⤙≍ "bvh" encode "yes"

# Encode no
⍤⤙≍ "ml" encode "no"

# Encode OMG
⍤⤙≍ "lnt" encode "OMG"

# Encode spaces
⍤⤙≍ "lnt" encode "O M G"

# Encode mindblowingly
⍤⤙≍ "nrmwy oldrm tob" encode "mindblowingly"

# Encode numbers
⍤⤙≍ "gvhgr mt123 gvhgr mt" encode "Testing,1 2 3, testing."

# Encode deep thought
⍤⤙≍ "gifgs rhurx grlm" encode "Truth is fiction."

# Encode all the letters
⍤⤙≍ "gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt" encode "The quick brown fox jumps over the lazy dog."

# Decode exercism
⍤⤙≍ "exercism" decode "vcvix rhn"

# Decode a sentence
⍤⤙≍ "anobstacleisoftenasteppingstone" decode "zmlyh gzxov rhlug vmzhg vkkrm thglm v"

# Decode numbers
⍤⤙≍ "testing123testing" decode "gvhgr mt123 gvhgr mt"

# Decode all the letters
⍤⤙≍ "thequickbrownfoxjumpsoverthelazydog" decode "gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt"

# Decode with too many spaces
⍤⤙≍ "exercism" decode "vc vix    r hn"

# Decode with no spaces
⍤⤙≍ "anobstacleisoftenasteppingstone" decode "zmlyhgzxovrhlugvmzhgvkkrmthglmv"

