~ "say.ua" ~ Say

# Zero
⍤⤙≍ (Some "zero") say 0

# One
⍤⤙≍ (Some "one") say 1

# Fourteen
⍤⤙≍ (Some "fourteen") say 14

# Twenty
⍤⤙≍ (Some "twenty") say 20

# Twenty-two
⍤⤙≍ (Some "twenty-two") say 22

# Thirty
⍤⤙≍ (Some "thirty") say 30

# Ninety-nine
⍤⤙≍ (Some "ninety-nine") say 99

# One hundred
⍤⤙≍ (Some "one hundred") say 100

# One hundred twenty-three
⍤⤙≍ (Some "one hundred twenty-three") say 123

# Two hundred
⍤⤙≍ (Some "two hundred") say 200

# Nine hundred ninety-nine
⍤⤙≍ (Some "nine hundred ninety-nine") say 999

# One thousand
⍤⤙≍ (Some "one thousand") say 1000

# One thousand two hundred thirty-four
⍤⤙≍ (Some "one thousand two hundred thirty-four") say 1234

# One million
⍤⤙≍ (Some "one million") say 1000000

# One million two thousand three hundred forty-five
⍤⤙≍ (Some "one million two thousand three hundred forty-five") say 1002345

# One billion
⍤⤙≍ (Some "one billion") say 1000000000

# A big number
⍤⤙≍ (Some "nine hundred eighty-seven billion six hundred fifty-four million three hundred twenty-one thousand one hundred twenty-three") say 987654321123

# Numbers below zero are out of range
⍤⤙≍ None say -1

# Numbers above 999,999,999,999 are out of range
⍤⤙≍ None say 1000000000000

