~ "wordy.ua" ~ Wordy

# Just a number
⍤⤙≍ 5 answer "What is 5?"

# Addition
⍤⤙≍ 2 answer "What is 1 plus 1?"

# More addition
⍤⤙≍ 55 answer "What is 53 plus 2?"

# Addition with negative numbers
⍤⤙≍ -11 answer "What is -1 plus -10?"

# Large addition
⍤⤙≍ 45801 answer "What is 123 plus 45678?"

# Subtraction
⍤⤙≍ 16 answer "What is 4 minus -12?"

# Multiplication
⍤⤙≍ -75 answer "What is -3 multiplied by 25?"

# Division
⍤⤙≍ -11 answer "What is 33 divided by -3?"

# Multiple additions
⍤⤙≍ 3 answer "What is 1 plus 1 plus 1?"

# Addition and subtraction
⍤⤙≍ 8 answer "What is 1 plus 5 minus -2?"

# Multiple subtraction
⍤⤙≍ 3 answer "What is 20 minus 4 minus 13?"

# Subtraction then addition
⍤⤙≍ 14 answer "What is 17 minus 6 plus 3?"

# Multiple multiplication
⍤⤙≍ -12 answer "What is 2 multiplied by -2 multiplied by 3?"

# Addition and multiplication
⍤⤙≍ -8 answer "What is -3 plus 7 multiplied by -2?"

# Multiple division
⍤⤙≍ 2 answer "What is -12 divided by 2 divided by -3?"

# Unknown operation
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is 52 cubed?")

# Non math question
⍤⤙≍ "TODO: insert error message" ⍣(answer "Who is the President of the United States?")

# Reject problem missing an operand
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is 1 plus?")

# Reject problem with no operands or operators
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is?")

# Reject two operations in a row
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is 1 plus plus 2?")

# Reject two numbers in a row
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is 1 plus 2 1?")

# Reject postfix notation
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is 1 2 plus?")

# Reject prefix notation
⍤⤙≍ "TODO: insert error message" ⍣(answer "What is plus 1 2?")
