~ "SOLUTION" ~ Hexadecimal

# Hexadecimal 1 is decimal 1
⍤⤙≍ 1 toDecimal "1"

# Hexadecimal c is decimal 12
⍤⤙≍ 12 toDecimal "c"

# Hexadecimal 10 is decimal 16
⍤⤙≍ 16 toDecimal "10"

# Hexadecimal af is decimal 175
⍤⤙≍ 175 toDecimal "af"

# Hexadecimal 100 is decimal 256
⍤⤙≍ 256 toDecimal "100"

# Hexadecimal 19ace is decimal 105166
⍤⤙≍ 105166 toDecimal "19ace"

# Hexadecimal 000000 is decimal 0
⍤⤙≍ 0 toDecimal "000000"

# Hexadecimal ffffff is decimal 16777215
⍤⤙≍ 16777215 toDecimal "ffffff"

# Hexadecimal ffff00 is decimal 16776960
⍤⤙≍ 16776960 toDecimal "ffff00"

# Hexadecimal carrot is decimal 0
⍤⤙≍ 0 toDecimal "carrot"

