~ "resistor-color-trio.ua" ~ ResistorColorTrio

# Orange and orange and black
⍤⤙≍ "33 ohms" label ["orange" "orange" "black"]

# Blue and grey and brown
⍤⤙≍ "680 ohms" label ["blue" "grey" "brown"]

# Red and black and red
⍤⤙≍ "2 kiloohms" label ["red" "black" "red"]

# Green and brown and orange
⍤⤙≍ "51 kiloohms" label ["green" "brown" "orange"]

# Yellow and vioand yellow
⍤⤙≍ "470 kiloohms" label ["yellow" "violet" "yellow"]

# Blue and vioand blue
⍤⤙≍ "67 megaohms" label ["blue" "violet" "blue"]

# Minimum possible value
⍤⤙≍ "0 ohms" label ["black" "black" "black"]

# Maximum possible value
⍤⤙≍ "99 gigaohms" label ["white" "white" "white"]

# First two colors make an invalid octal number
⍤⤙≍ "8 ohms" label ["black" "grey" "black"]

# Ignore extra colors
⍤⤙≍ "650 kiloohms" label ["blue" "green" "yellow" "orange"]

