~ "raindrops.ua" ~ Raindrops

# The sound for 1 is 1
⍤⤙≍ "1" convert 1

# The sound for 3 is Pling
⍤⤙≍ "Pling" convert 3

# The sound for 5 is Plang
⍤⤙≍ "Plang" convert 5

# The sound for 7 is Plong
⍤⤙≍ "Plong" convert 7

# The sound for 6 is Pling as it has a factor 3
⍤⤙≍ "Pling" convert 6

# 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base
⍤⤙≍ "8" convert 8

# The sound for 9 is Pling as it has a factor 3
⍤⤙≍ "Pling" convert 9

# The sound for 10 is Plang as it has a factor 5
⍤⤙≍ "Plang" convert 10

# The sound for 14 is Plong as it has a factor of 7
⍤⤙≍ "Plong" convert 14

# The sound for 15 is PlingPlang as it has factors 3 and 5
⍤⤙≍ "PlingPlang" convert 15

# The sound for 21 is PlingPlong as it has factors 3 and 7
⍤⤙≍ "PlingPlong" convert 21

# The sound for 25 is Plang as it has a factor 5
⍤⤙≍ "Plang" convert 25

# The sound for 27 is Pling as it has a factor 3
⍤⤙≍ "Pling" convert 27

# The sound for 35 is PlangPlong as it has factors 5 and 7
⍤⤙≍ "PlangPlong" convert 35

# The sound for 49 is Plong as it has a factor 7
⍤⤙≍ "Plong" convert 49

# The sound for 52 is 52
⍤⤙≍ "52" convert 52

# The sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7
⍤⤙≍ "PlingPlangPlong" convert 105

# The sound for 3125 is Plang as it has a factor 5
⍤⤙≍ "Plang" convert 3125

