~ "difference-of-squares.ua" ~ DifferenceOfSquares

# Square of sum 1
⍤⤙≍ 1 squareOfSum 1

# Square of sum 5
⍤⤙≍ 225 squareOfSum 5

# Square of sum 100
⍤⤙≍ 25502500 squareOfSum 100

# Sum of squares 1
⍤⤙≍ 1 sumOfSquares 1

# Sum of squares 5
⍤⤙≍ 55 sumOfSquares 5

# Sum of squares 100
⍤⤙≍ 338350 sumOfSquares 100

# Difference of squares 1
⍤⤙≍ 0 differenceOfSquares 1

# Difference of squares 5
⍤⤙≍ 170 differenceOfSquares 5

# Difference of squares 100
⍤⤙≍ 25164150 differenceOfSquares 100

