~ "killer-sudoku-helper.ua" ~ KillerSudokuHelper

# 1
⍤⤙≍ [[1]] combinations [] 1 1

# 2
⍤⤙≍ [[2]] combinations [] 1 2

# 3
⍤⤙≍ [[3]] combinations [] 1 3

# 4
⍤⤙≍ [[4]] combinations [] 1 4

# 5
⍤⤙≍ [[5]] combinations [] 1 5

# 6
⍤⤙≍ [[6]] combinations [] 1 6

# 7
⍤⤙≍ [[7]] combinations [] 1 7

# 8
⍤⤙≍ [[8]] combinations [] 1 8

# 9
⍤⤙≍ [[9]] combinations [] 1 9

# Cage with sum 45 contains all digits 1:9
⍤⤙≍ [[1 2 3 4 5 6 7 8 9]] combinations [] 9 45

# Cage with only 1 possible combination
⍤⤙≍ [[1 2 4]] combinations [] 3 7

# Cage with several combinations
⍤⤙≍ [[1 9] [2 8] [3 7] [4 6]] combinations [] 2 10

# Cage with several combinations that is restricted
⍤⤙≍ [[2 8] [3 7]] combinations [1 4] 2 10

