~ "acronym.ua" ~ Acronym

# Basic
⍤⤙≍ "PNG" abbreviate "Portable Network Graphics"

# Lowercase words
⍤⤙≍ "ROR" abbreviate "Ruby on Rails"

# Punctuation
⍤⤙≍ "FIFO" abbreviate "First In, First Out"

# All caps word
⍤⤙≍ "GIMP" abbreviate "GNU Image Manipulation Program"

# Punctuation without whitespace
⍤⤙≍ "CMOS" abbreviate "Complementary metal-oxide semiconductor"

# Very long abbreviation
⍤⤙≍ "ROTFLSHTMDCOALM" abbreviate "Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me"

# Consecutive delimiters
⍤⤙≍ "SIMUFTA" abbreviate "Something - I made up from thin air"

# Apostrophes
⍤⤙≍ "HC" abbreviate "Halley's Comet"

# Underscore emphasis
⍤⤙≍ "TRNT" abbreviate "The Road _Not_ Taken"

