~ "pig-latin.ua" ~ PigLatin

# Word beginning with a
⍤⤙≍ "appleay" translate "apple"

# Word beginning with e
⍤⤙≍ "earay" translate "ear"

# Word beginning with i
⍤⤙≍ "iglooay" translate "igloo"

# Word beginning with o
⍤⤙≍ "objectay" translate "object"

# Word beginning with u
⍤⤙≍ "underay" translate "under"

# Word beginning with a vowel and followed by a qu
⍤⤙≍ "equalay" translate "equal"

# Word beginning with p
⍤⤙≍ "igpay" translate "pig"

# Word beginning with k
⍤⤙≍ "oalakay" translate "koala"

# Word beginning with x
⍤⤙≍ "enonxay" translate "xenon"

# Word beginning with q without a following u
⍤⤙≍ "atqay" translate "qat"

# Word beginning with ch
⍤⤙≍ "airchay" translate "chair"

# Word beginning with qu
⍤⤙≍ "eenquay" translate "queen"

# Word beginning with qu and a preceding consonant
⍤⤙≍ "aresquay" translate "square"

# Word beginning with th
⍤⤙≍ "erapythay" translate "therapy"

# Word beginning with thr
⍤⤙≍ "ushthray" translate "thrush"

# Word beginning with sch
⍤⤙≍ "oolschay" translate "school"

# Word beginning with yt
⍤⤙≍ "yttriaay" translate "yttria"

# Word beginning with xr
⍤⤙≍ "xrayay" translate "xray"

# Y is treated like a consonant at the beginning of a word
⍤⤙≍ "ellowyay" translate "yellow"

# Y is treated like a vowel at the end of a consonant cluster
⍤⤙≍ "ythmrhay" translate "rhythm"

# Y as second letter in two letter word
⍤⤙≍ "ymay" translate "my"

# A whole phrase
⍤⤙≍ "ickquay astfay unray" translate "quick fast run"
