~ "armstrong-numbers.ua" ~ ArmstrongNumbers

# Zero is an Armstrong number
⍤⤙≍ 1 isArmstrongNumber 0

# Single-digit numbers are Armstrong numbers
⍤⤙≍ 1 isArmstrongNumber 5

# There are no two-digit Armstrong numbers
⍤⤙≍ 0 isArmstrongNumber 10

# Three-digit number that is an Armstrong number
⍤⤙≍ 1 isArmstrongNumber 153

# Three-digit number that is not an Armstrong number
⍤⤙≍ 0 isArmstrongNumber 100

# Four-digit number that is an Armstrong number
⍤⤙≍ 1 isArmstrongNumber 9474

# Four-digit number that is not an Armstrong number
⍤⤙≍ 0 isArmstrongNumber 9475

# Seven-digit number that is an Armstrong number
⍤⤙≍ 1 isArmstrongNumber 9926315

# Seven-digit number that is not an Armstrong number
⍤⤙≍ 0 isArmstrongNumber 9926314

