~ "book-store.ua" ~ BookStore

# Only a single book
⍤⤙≍ 8m total [1]

# Two of the same book
⍤⤙≍ 16m total [2 2]

# Empty basket
⍤⤙≍ 0m total []

# Two different books
⍤⤙≍ 15.2m total [1 2]

# Three different books
⍤⤙≍ 21.6m total [1 2 3]

# Four different books
⍤⤙≍ 25.6m total [1 2 3 4]

# Five different books
⍤⤙≍ 30m total [1 2 3 4 5]

# Two groups of four is cheaper than group of five plus group of three
⍤⤙≍ 51.2m total [1 1 2 2 3 3 4 5]

# Two groups of four is cheaper than groups of five and three
⍤⤙≍ 51.2m total [1 1 2 3 4 4 5 5]

# Group of four plus group of two is cheaper than two groups of three
⍤⤙≍ 40.8m total [1 1 2 2 3 4]

# Two each of first four books and one copy each of rest
⍤⤙≍ 55.6m total [1 1 2 2 3 3 4 4 5]

# Two copies of each book
⍤⤙≍ 60m total [1 1 2 2 3 3 4 4 5 5]

# Three copies of first book and two each of remaining
⍤⤙≍ 68m total [1 1 2 2 3 3 4 4 5 5 1]

# Three each of first two books and two each of remaining books
⍤⤙≍ 75.2m total [1 1 2 2 3 3 4 4 5 5 1 2]

# Four groups of four are cheaper than two groups each of five and three
⍤⤙≍ 102.4m total [1 1 2 2 3 3 4 5 1 1 2 2 3 3 4 5]

# Check that groups of four are created properly even when there are more groups of three than groups of five
⍤⤙≍ 145.6m total [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 5 5]

# One group of one and four is cheaper than one group of two and three
⍤⤙≍ 33.6m total [1 1 2 3 4]

# One group of one and two plus three groups of four is cheaper than one group of each size
⍤⤙≍ 100m total [1 2 2 3 3 3 4 4 4 4 5 5 5 5 5]
