~ "yacht.ua" ~ Yacht

# Yacht
⍤⤙≍ 50 score Category.Yacht [Die.Five Die.Five Die.Five Die.Five Die.Five]

# Not Yacht
⍤⤙≍ 0 score Category.Yacht [Die.One Die.Three Die.Three Die.Two Die.Five]

# Ones
⍤⤙≍ 3 score Category.Ones [Die.One Die.One Die.One Die.Three Die.Five]

# Ones, out of order
⍤⤙≍ 3 score Category.Ones [Die.Three Die.One Die.One Die.Five Die.One]

# No ones
⍤⤙≍ 0 score Category.Ones [Die.Four Die.Three Die.Six Die.Five Die.Five]

# Twos
⍤⤙≍ 2 score Category.Twos [Die.Two Die.Three Die.Four Die.Five Die.Six]

# Fours
⍤⤙≍ 8 score Category.Fours [Die.One Die.Four Die.One Die.Four Die.One]

# Yacht counted as threes
⍤⤙≍ 15 score Category.Threes [Die.Three Die.Three Die.Three Die.Three Die.Three]

# Yacht of 3s counted as fives
⍤⤙≍ 0 score Category.Fives [Die.Three Die.Three Die.Three Die.Three Die.Three]

# Fives
⍤⤙≍ 10 score Category.Fives [Die.One Die.Five Die.Three Die.Five Die.Three]

# Sixes
⍤⤙≍ 6 score Category.Sixes [Die.Two Die.Three Die.Four Die.Five Die.Six]

# Full house two small, three big
⍤⤙≍ 16 score Category.FullHouse [Die.Two Die.Two Die.Four Die.Four Die.Four]

# Full house three small, two big
⍤⤙≍ 19 score Category.FullHouse [Die.Five Die.Three Die.Three Die.Five Die.Three]

# Two pair is not a full house
⍤⤙≍ 0 score Category.FullHouse [Die.Two Die.Two Die.Four Die.Four Die.Five]

# Four of a kind is not a full house
⍤⤙≍ 0 score Category.FullHouse [Die.One Die.Four Die.Four Die.Four Die.Four]

# Yacht is not a full house
⍤⤙≍ 0 score Category.FullHouse [Die.Two Die.Two Die.Two Die.Two Die.Two]

# Four of a Kind
⍤⤙≍ 24 score Category.FourOfAKind [Die.Six Die.Six Die.Four Die.Six Die.Six]

# Yacht can be scored as Four of a Kind
⍤⤙≍ 12 score Category.FourOfAKind [Die.Three Die.Three Die.Three Die.Three Die.Three]

# Full house is not Four of a Kind
⍤⤙≍ 0 score Category.FourOfAKind [Die.Three Die.Three Die.Three Die.Five Die.Five]

# Little Straight
⍤⤙≍ 30 score Category.LittleStraight [Die.Three Die.Five Die.Four Die.One Die.Two]

# Little Straight as Big Straight
⍤⤙≍ 0 score Category.BigStraight [Die.One Die.Two Die.Three Die.Four Die.Five]

# Four in order but not a little straight
⍤⤙≍ 0 score Category.LittleStraight [Die.One Die.One Die.Two Die.Three Die.Four]

# No pairs but not a little straight
⍤⤙≍ 0 score Category.LittleStraight [Die.One Die.Two Die.Three Die.Four Die.Six]

# Minimum is 1, maximum is 5, but not a little straight
⍤⤙≍ 0 score Category.LittleStraight [Die.One Die.One Die.Three Die.Four Die.Five]

# Big Straight
⍤⤙≍ 30 score Category.BigStraight [Die.Four Die.Six Die.Two Die.Five Die.Three]

# Big Straight as little straight
⍤⤙≍ 0 score Category.LittleStraight [Die.Six Die.Five Die.Four Die.Three Die.Two]

# No pairs but not a big straight
⍤⤙≍ 0 score Category.BigStraight [Die.Six Die.Five Die.Four Die.Three Die.One]

# Choice
⍤⤙≍ 23 score Category.Choice [Die.Three Die.Three Die.Five Die.Six Die.Six]

# Yacht as choice
⍤⤙≍ 10 score Category.Choice [Die.Two Die.Two Die.Two Die.Two Die.Two]
