module TrinaryTest



# Trinary_1_is_decimal_1
⍤⤙≍ 1 toDecimal "1"

# Trinary_2_is_decimal_2
⍤⤙≍ 2 toDecimal "2"

# Trinary_10_is_decimal_3
⍤⤙≍ 3 toDecimal "10"

# Trinary_11_is_decimal_4
⍤⤙≍ 4 toDecimal "11"

# Trinary_100_is_decimal_9
⍤⤙≍ 9 toDecimal "100"

# Trinary_112_is_decimal_14
⍤⤙≍ 14 toDecimal "112"

# Trinary_222_is_decimal_26
⍤⤙≍ 26 toDecimal "222"

# Trinary_1122000120_is_decimal_32091
⍤⤙≍ 32091 toDecimal "1122000120"

# Invalid_trinary_digits_returns_0
⍤⤙≍ 0 toDecimal "1234"

# Invalid_word_as_input_returns_0
⍤⤙≍ 0 toDecimal "carrot"

# Invalid_numbers_with_letters_as_input_returns_0
⍤⤙≍ 0 toDecimal "0a1b2c"

