~ "bob.ua" ~ Bob

# Stating something
⍤⤙≍ "Whatever." response "Tom-ay-to, tom-aaaah-to."

# Shouting
⍤⤙≍ "Whoa, chill out!" response "WATCH OUT!"

# Shouting gibberish
⍤⤙≍ "Whoa, chill out!" response "FCECDFCAAB"

# Asking a question
⍤⤙≍ "Sure." response "Does this cryogenic chamber make me look fat?"

# Asking a numeric question
⍤⤙≍ "Sure." response "You are, what, like 15?"

# Asking gibberish
⍤⤙≍ "Sure." response "fffbbcbeab?"

# Talking forcefully
⍤⤙≍ "Whatever." response "Hi there!"

# Using acronyms in regular speech
⍤⤙≍ "Whatever." response "It's OK if you don't want to go work for NASA."

# Forceful question
⍤⤙≍ "Calm down, I know what I'm doing!" response "WHAT'S GOING ON?"

# Shouting numbers
⍤⤙≍ "Whoa, chill out!" response "1, 2, 3 GO!"

# No letters
⍤⤙≍ "Whatever." response "1, 2, 3"

# Question with no letters
⍤⤙≍ "Sure." response "4?"

# Shouting with special characters
⍤⤙≍ "Whoa, chill out!" response "ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!"

# Shouting with no exclamation mark
⍤⤙≍ "Whoa, chill out!" response "I HATE THE DENTIST"

# Statement containing question mark
⍤⤙≍ "Whatever." response "Ending with ? means a question."

# Non-letters with question
⍤⤙≍ "Sure." response ":) ?"

# Prattling on
⍤⤙≍ "Sure." response "Wait! Hang on. Are you going to be OK?"

# Silence
⍤⤙≍ "Fine. Be that way!" response ""

# Prolonged silence
⍤⤙≍ "Fine. Be that way!" response "          "

# Alternate silence
⍤⤙≍ "Fine. Be that way!" response "\t\t\t\t\t\t\t\t\t\t"

# Multiple line question
⍤⤙≍ "Whatever." response "\nDoes this cryogenic chamber make me look fat?\nNo."

# Starting with whitespace
⍤⤙≍ "Whatever." response "         hmmmmmmm..."

# Ending with whitespace
⍤⤙≍ "Sure." response "Okay if like my  spacebar  quite a bit?   "

# Other whitespace
⍤⤙≍ "Fine. Be that way!" response "\n\r \t"

# Non-question ending with whitespace
⍤⤙≍ "Whatever." response "This is a statement ending with whitespace      "

