~ "meetup.ua" ~ Meetup

# When teenth Monday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 5, 13)) meetup 2013 5 Week.Teenth DayOfWeek.Monday

# When teenth Monday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 8, 19)) meetup 2013 8 Week.Teenth DayOfWeek.Monday

# When teenth Monday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 9, 16)) meetup 2013 9 Week.Teenth DayOfWeek.Monday

# When teenth Tuesday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 3, 19)) meetup 2013 3 Week.Teenth DayOfWeek.Tuesday

# When teenth Tuesday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 4, 16)) meetup 2013 4 Week.Teenth DayOfWeek.Tuesday

# When teenth Tuesday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 8, 13)) meetup 2013 8 Week.Teenth DayOfWeek.Tuesday

# When teenth Wednesday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 1, 16)) meetup 2013 1 Week.Teenth DayOfWeek.Wednesday

# When teenth Wednesday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 2, 13)) meetup 2013 2 Week.Teenth DayOfWeek.Wednesday

# When teenth Wednesday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 6, 19)) meetup 2013 6 Week.Teenth DayOfWeek.Wednesday

# When teenth Thursday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 5, 16)) meetup 2013 5 Week.Teenth DayOfWeek.Thursday

# When teenth Thursday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 6, 13)) meetup 2013 6 Week.Teenth DayOfWeek.Thursday

# When teenth Thursday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 9, 19)) meetup 2013 9 Week.Teenth DayOfWeek.Thursday

# When teenth Friday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 4, 19)) meetup 2013 4 Week.Teenth DayOfWeek.Friday

# When teenth Friday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 8, 16)) meetup 2013 8 Week.Teenth DayOfWeek.Friday

# When teenth Friday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 9, 13)) meetup 2013 9 Week.Teenth DayOfWeek.Friday

# When teenth Saturday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 2, 16)) meetup 2013 2 Week.Teenth DayOfWeek.Saturday

# When teenth Saturday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 4, 13)) meetup 2013 4 Week.Teenth DayOfWeek.Saturday

# When teenth Saturday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 10, 19)) meetup 2013 10 Week.Teenth DayOfWeek.Saturday

# When teenth Sunday is the 19th, the last day of the teenth week
⍤⤙≍ (DateTime(2013, 5, 19)) meetup 2013 5 Week.Teenth DayOfWeek.Sunday

# When teenth Sunday is some day in the middle of the teenth week
⍤⤙≍ (DateTime(2013, 6, 16)) meetup 2013 6 Week.Teenth DayOfWeek.Sunday

# When teenth Sunday is the 13th, the first day of the teenth week
⍤⤙≍ (DateTime(2013, 10, 13)) meetup 2013 10 Week.Teenth DayOfWeek.Sunday

# When first Monday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 3, 4)) meetup 2013 3 Week.First DayOfWeek.Monday

# When first Monday is the 1st, the first day of the first week
⍤⤙≍ (DateTime(2013, 4, 1)) meetup 2013 4 Week.First DayOfWeek.Monday

# When first Tuesday is the 7th, the last day of the first week
⍤⤙≍ (DateTime(2013, 5, 7)) meetup 2013 5 Week.First DayOfWeek.Tuesday

# When first Tuesday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 6, 4)) meetup 2013 6 Week.First DayOfWeek.Tuesday

# When first Wednesday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 7, 3)) meetup 2013 7 Week.First DayOfWeek.Wednesday

# When first Wednesday is the 7th, the last day of the first week
⍤⤙≍ (DateTime(2013, 8, 7)) meetup 2013 8 Week.First DayOfWeek.Wednesday

# When first Thursday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 9, 5)) meetup 2013 9 Week.First DayOfWeek.Thursday

# When first Thursday is another day in the middle of the first week
⍤⤙≍ (DateTime(2013, 10, 3)) meetup 2013 10 Week.First DayOfWeek.Thursday

# When first Friday is the 1st, the first day of the first week
⍤⤙≍ (DateTime(2013, 11, 1)) meetup 2013 11 Week.First DayOfWeek.Friday

# When first Friday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 12, 6)) meetup 2013 12 Week.First DayOfWeek.Friday

# When first Saturday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 1, 5)) meetup 2013 1 Week.First DayOfWeek.Saturday

# When first Saturday is another day in the middle of the first week
⍤⤙≍ (DateTime(2013, 2, 2)) meetup 2013 2 Week.First DayOfWeek.Saturday

# When first Sunday is some day in the middle of the first week
⍤⤙≍ (DateTime(2013, 3, 3)) meetup 2013 3 Week.First DayOfWeek.Sunday

# When first Sunday is the 7th, the last day of the first week
⍤⤙≍ (DateTime(2013, 4, 7)) meetup 2013 4 Week.First DayOfWeek.Sunday

# When second Monday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 3, 11)) meetup 2013 3 Week.Second DayOfWeek.Monday

# When second Monday is the 8th, the first day of the second week
⍤⤙≍ (DateTime(2013, 4, 8)) meetup 2013 4 Week.Second DayOfWeek.Monday

# When second Tuesday is the 14th, the last day of the second week
⍤⤙≍ (DateTime(2013, 5, 14)) meetup 2013 5 Week.Second DayOfWeek.Tuesday

# When second Tuesday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 6, 11)) meetup 2013 6 Week.Second DayOfWeek.Tuesday

# When second Wednesday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 7, 10)) meetup 2013 7 Week.Second DayOfWeek.Wednesday

# When second Wednesday is the 14th, the last day of the second week
⍤⤙≍ (DateTime(2013, 8, 14)) meetup 2013 8 Week.Second DayOfWeek.Wednesday

# When second Thursday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 9, 12)) meetup 2013 9 Week.Second DayOfWeek.Thursday

# When second Thursday is another day in the middle of the second week
⍤⤙≍ (DateTime(2013, 10, 10)) meetup 2013 10 Week.Second DayOfWeek.Thursday

# When second Friday is the 8th, the first day of the second week
⍤⤙≍ (DateTime(2013, 11, 8)) meetup 2013 11 Week.Second DayOfWeek.Friday

# When second Friday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 12, 13)) meetup 2013 12 Week.Second DayOfWeek.Friday

# When second Saturday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 1, 12)) meetup 2013 1 Week.Second DayOfWeek.Saturday

# When second Saturday is another day in the middle of the second week
⍤⤙≍ (DateTime(2013, 2, 9)) meetup 2013 2 Week.Second DayOfWeek.Saturday

# When second Sunday is some day in the middle of the second week
⍤⤙≍ (DateTime(2013, 3, 10)) meetup 2013 3 Week.Second DayOfWeek.Sunday

# When second Sunday is the 14th, the last day of the second week
⍤⤙≍ (DateTime(2013, 4, 14)) meetup 2013 4 Week.Second DayOfWeek.Sunday

# When third Monday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 3, 18)) meetup 2013 3 Week.Third DayOfWeek.Monday

# When third Monday is the 15th, the first day of the third week
⍤⤙≍ (DateTime(2013, 4, 15)) meetup 2013 4 Week.Third DayOfWeek.Monday

# When third Tuesday is the 21st, the last day of the third week
⍤⤙≍ (DateTime(2013, 5, 21)) meetup 2013 5 Week.Third DayOfWeek.Tuesday

# When third Tuesday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 6, 18)) meetup 2013 6 Week.Third DayOfWeek.Tuesday

# When third Wednesday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 7, 17)) meetup 2013 7 Week.Third DayOfWeek.Wednesday

# When third Wednesday is the 21st, the last day of the third week
⍤⤙≍ (DateTime(2013, 8, 21)) meetup 2013 8 Week.Third DayOfWeek.Wednesday

# When third Thursday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 9, 19)) meetup 2013 9 Week.Third DayOfWeek.Thursday

# When third Thursday is another day in the middle of the third week
⍤⤙≍ (DateTime(2013, 10, 17)) meetup 2013 10 Week.Third DayOfWeek.Thursday

# When third Friday is the 15th, the first day of the third week
⍤⤙≍ (DateTime(2013, 11, 15)) meetup 2013 11 Week.Third DayOfWeek.Friday

# When third Friday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 12, 20)) meetup 2013 12 Week.Third DayOfWeek.Friday

# When third Saturday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 1, 19)) meetup 2013 1 Week.Third DayOfWeek.Saturday

# When third Saturday is another day in the middle of the third week
⍤⤙≍ (DateTime(2013, 2, 16)) meetup 2013 2 Week.Third DayOfWeek.Saturday

# When third Sunday is some day in the middle of the third week
⍤⤙≍ (DateTime(2013, 3, 17)) meetup 2013 3 Week.Third DayOfWeek.Sunday

# When third Sunday is the 21st, the last day of the third week
⍤⤙≍ (DateTime(2013, 4, 21)) meetup 2013 4 Week.Third DayOfWeek.Sunday

# When fourth Monday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 3, 25)) meetup 2013 3 Week.Fourth DayOfWeek.Monday

# When fourth Monday is the 22nd, the first day of the fourth week
⍤⤙≍ (DateTime(2013, 4, 22)) meetup 2013 4 Week.Fourth DayOfWeek.Monday

# When fourth Tuesday is the 28th, the last day of the fourth week
⍤⤙≍ (DateTime(2013, 5, 28)) meetup 2013 5 Week.Fourth DayOfWeek.Tuesday

# When fourth Tuesday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 6, 25)) meetup 2013 6 Week.Fourth DayOfWeek.Tuesday

# When fourth Wednesday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 7, 24)) meetup 2013 7 Week.Fourth DayOfWeek.Wednesday

# When fourth Wednesday is the 28th, the last day of the fourth week
⍤⤙≍ (DateTime(2013, 8, 28)) meetup 2013 8 Week.Fourth DayOfWeek.Wednesday

# When fourth Thursday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 9, 26)) meetup 2013 9 Week.Fourth DayOfWeek.Thursday

# When fourth Thursday is another day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 10, 24)) meetup 2013 10 Week.Fourth DayOfWeek.Thursday

# When fourth Friday is the 22nd, the first day of the fourth week
⍤⤙≍ (DateTime(2013, 11, 22)) meetup 2013 11 Week.Fourth DayOfWeek.Friday

# When fourth Friday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 12, 27)) meetup 2013 12 Week.Fourth DayOfWeek.Friday

# When fourth Saturday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 1, 26)) meetup 2013 1 Week.Fourth DayOfWeek.Saturday

# When fourth Saturday is another day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 2, 23)) meetup 2013 2 Week.Fourth DayOfWeek.Saturday

# When fourth Sunday is some day in the middle of the fourth week
⍤⤙≍ (DateTime(2013, 3, 24)) meetup 2013 3 Week.Fourth DayOfWeek.Sunday

# When fourth Sunday is the 28th, the last day of the fourth week
⍤⤙≍ (DateTime(2013, 4, 28)) meetup 2013 4 Week.Fourth DayOfWeek.Sunday

# Last Monday in a month with four Mondays
⍤⤙≍ (DateTime(2013, 3, 25)) meetup 2013 3 Week.Last DayOfWeek.Monday

# Last Monday in a month with five Mondays
⍤⤙≍ (DateTime(2013, 4, 29)) meetup 2013 4 Week.Last DayOfWeek.Monday

# Last Tuesday in a month with four Tuesdays
⍤⤙≍ (DateTime(2013, 5, 28)) meetup 2013 5 Week.Last DayOfWeek.Tuesday

# Last Tuesday in another month with four Tuesdays
⍤⤙≍ (DateTime(2013, 6, 25)) meetup 2013 6 Week.Last DayOfWeek.Tuesday

# Last Wednesday in a month with five Wednesdays
⍤⤙≍ (DateTime(2013, 7, 31)) meetup 2013 7 Week.Last DayOfWeek.Wednesday

# Last Wednesday in a month with four Wednesdays
⍤⤙≍ (DateTime(2013, 8, 28)) meetup 2013 8 Week.Last DayOfWeek.Wednesday

# Last Thursday in a month with four Thursdays
⍤⤙≍ (DateTime(2013, 9, 26)) meetup 2013 9 Week.Last DayOfWeek.Thursday

# Last Thursday in a month with five Thursdays
⍤⤙≍ (DateTime(2013, 10, 31)) meetup 2013 10 Week.Last DayOfWeek.Thursday

# Last Friday in a month with five Fridays
⍤⤙≍ (DateTime(2013, 11, 29)) meetup 2013 11 Week.Last DayOfWeek.Friday

# Last Friday in a month with four Fridays
⍤⤙≍ (DateTime(2013, 12, 27)) meetup 2013 12 Week.Last DayOfWeek.Friday

# Last Saturday in a month with four Saturdays
⍤⤙≍ (DateTime(2013, 1, 26)) meetup 2013 1 Week.Last DayOfWeek.Saturday

# Last Saturday in another month with four Saturdays
⍤⤙≍ (DateTime(2013, 2, 23)) meetup 2013 2 Week.Last DayOfWeek.Saturday

# Last Sunday in a month with five Sundays
⍤⤙≍ (DateTime(2013, 3, 31)) meetup 2013 3 Week.Last DayOfWeek.Sunday

# Last Sunday in a month with four Sundays
⍤⤙≍ (DateTime(2013, 4, 28)) meetup 2013 4 Week.Last DayOfWeek.Sunday

# When last Wednesday in February in a leap year is the 29th
⍤⤙≍ (DateTime(2012, 2, 29)) meetup 2012 2 Week.Last DayOfWeek.Wednesday

# Last Wednesday in December that is also the last day of the year
⍤⤙≍ (DateTime(2014, 12, 31)) meetup 2014 12 Week.Last DayOfWeek.Wednesday

# When last Sunday in February in a non-leap year is not the 29th
⍤⤙≍ (DateTime(2015, 2, 22)) meetup 2015 2 Week.Last DayOfWeek.Sunday

# When first Friday is the 7th, the last day of the first week
⍤⤙≍ (DateTime(2012, 12, 7)) meetup 2012 12 Week.First DayOfWeek.Friday

