~ "resistor-color-duo.ua" ~ ResistorColorDuo

# Brown and black
⍤⤙≍ 10 value ["brown" "black"]

# Blue and grey
⍤⤙≍ 68 value ["blue" "grey"]

# Yellow and violet
⍤⤙≍ 47 value ["yellow" "violet"]

# White and red
⍤⤙≍ 92 value ["white" "red"]

# Orange and orange
⍤⤙≍ 33 value ["orange" "orange"]

# Ignore additional colors
⍤⤙≍ 51 value ["green" "brown" "orange"]

# Black and brown, one-digit
⍤⤙≍ 1 value ["black" "brown"]

