name: Check Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup .NET
        uses: actions/setup-dotnet@87c6e1177627274101056947ed58ce11ef42d658
        with:
          dotnet-version: "9.0.101"

      - name: Validate Code Snippets
        run: pwsh ./bin/check-code-snippets.ps1
