name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-dotnet@bf4cd79173c0290c09af17cf9003ca2f32edea40
        with:
          dotnet-version: "9.0.101"

      - name: Run tests
        run: pwsh ./bin/test.ps1
